# ----- CLEO -----
# File: rshaft1d_config.yaml
# Project: config
# Created Date: Thursday 18th April 2024
# Author: Clara Bayley (CB)
# Additional Contributors:
# -----
# License: BSD 3-Clause "New" or "Revised" License
# https://opensource.org/licenses/BSD-3-Clause
# -----
# Copyright (c) 2023 MPI-M, Clara Bayley
# -----
# File Description:
# Configuration file for CLEO 1-D rainshaft example with constant thermodynamics.
# Note: The initial superdroplets data read from file "initsupers_filename" can be made with
# CLEO's cleopy module (see Python script "create_initsuperdropsbinary_script.py" for example of usage).
# Likewise the "grid_filename" can be made using cleopy (see "create_gbxboundariesbinary_script.py"),
# and so can the thermodynamics files when using coupled thermodynamics "fromfile".
#

### Initialization Parameters for rshaft1d_inputfiles.py ###
python_inputfiles:
  zgrid_max: 2500                              # domain size in z [m]
  xgrid_max: 20                                # domain size in x [m]
  ygrid_max: 20                                # domain size in y [m]
  sd_zlim: 800                                 # min z coord of initial superdroplets
  nsupers_pergbx: 256                          # number of SDs per gridbox above sd_zlim <- note(!) must be consistent with maxnsupers (see below)
  rspan:                                       # [min, max] range of radii to sample [m]
    - 3e-9
    - 5e-5
  dryr_sf: 1.0                                 # dryradii are 1/sf of radii [m]
  geomeans:                                    # geometric means of trimodal Lognormal distribution
    - 0.02e-6
    - 0.2e-6
    - 3.5e-6
  geosigs:                                     # geometric stddevs of trimodal Lognormal distribution
    - 1.55
    - 2.3
    - 2
  scalefacs:                                   # scale factors of peaks in trimodal Lognormal distribution
    - 1.0
    - 0.3
    - 0.025
  numconc: 1.325e9                             # total no. conc of real droplets [m^-3]
  thermo_PRESSz0: 101315                       # settings for thermodynamics profiles [Pa]
  thermo_TEMPz0: 297.9                         # [K]
  thermo_qvapz0: 0.016                         # [Kg/Kg]
  thermo_Zbase: 800                            # [m]
  thermo_TEMPlapses:                           # -dT/dz [below, above] Zbase; [K/km]
    - 9.8
    - 6.5
  thermo_qvaplapses:                           # -dvap/dz [below, above] Zbase; [g/Kg km^-1]
    - 2.97
    - "saturated"
  thermo_WVEL: 4.0                             # max or constant vertical wind (see Wlength) [m/s]
  thermo_Wlength: 1000                         # [m] use constant WVEL with Wlength=0.0, else sinusoidal 1-D profile below cloud base

### Kokkos Initialization Parameters ###
kokkos_settings:
  num_threads: 256                                          # number of threads for host parallel backend

### SDM Runtime Parameters ###
domain:
  nspacedims : 1                                             # no. of spatial dimensions to model
  ngbxs : 125                                                # total number of Gbxs
  maxnsupers: 21760                                          # maximum number of SDs

timesteps:
  CONDTSTEP : 1                                              # time between SD condensation [s]
  COLLTSTEP : 1                                              # time between SD collision [s]
  MOTIONTSTEP : 2                                            # time between SDM motion [s]
  COUPLTSTEP : 2400                                          # time between dynamic couplings [s]
  OBSTSTEP : 120                                             # time between SDM observations [s]
  T_END : 2400                                               # time span of integration from 0s to T_END [s]

### Initialisation Parameters ###
inputfiles:
  constants_filename : ./libs/cleoconstants.hpp             # name of file for values of physical constants
  grid_filename : ./build/share/rshaft1d_dimlessGBxboundaries.dat    # binary filename for initialisation of GBxs / GbxMaps

initsupers:
  type: frombinary                                           # type of initialisation of super-droplets
  initsupers_filename : ./build/share/rshaft1d_dimlessSDsinit.dat    # binary filename for initialisation of SDs

### Output Parameters ###
outputdata:
  setup_filename : ./build/bin/rshaft1d_setup.txt                    # .txt filename to copy configuration to
  zarrbasedir : ./build/bin/rshaft1d_sol.zarr                        # zarr store base directory
  maxchunk : 2500000                                         # maximum no. of elements in chunks of zarr store array

### Microphysics Parameters ###
microphysics:
  condensation:
    do_alter_thermo : false                                  # true = cond/evap alters the thermodynamic state
    maxniters : 50                                           # maximum no. iterations of Newton Raphson Method
    MINSUBTSTEP : 0.001                                      # minimum subtimestep in cases of substepping [s]
    rtol : 0.0                                               # relative tolerance for implicit Euler integration
    atol : 0.01                                              # absolute tolerance for implicit Euler integration
  coalescence:
    constcoaleff:
      coaleff: 1.0                                            # constant coalescence efficiency

### Coupled Dynamics Parameters ###
coupled_dynamics:
  type : fromfile                                            # type of coupled dynamics to configure
  press : ./build/share/rshaft1d_dimlessthermo_press.dat             # binary filename for pressure
  temp : ./build/share/rshaft1d_dimlessthermo_temp.dat               # binary filename for temperature
  qvap : ./build/share/rshaft1d_dimlessthermo_qvap.dat               # binary filename for vapour mixing ratio
  qcond : ./build/share/rshaft1d_dimlessthermo_qcond.dat             # binary filename for liquid mixing ratio
  wvel : ./build/share/rshaft1d_dimlessthermo_wvel.dat               # binary filename for vertical (coord3) velocity
