# ----- CLEO -----
# File: kokkostools_config.yaml
# Project: config
# Created Date: Thursday 18th April 2024
# Author: Clara Bayley (CB)
# Additional Contributors:
# -----
# License: BSD 3-Clause "New" or "Revised" License
# https://opensource.org/licenses/BSD-3-Clause
# -----
# Copyright (c) 2023 MPI-M, Clara Bayley
# -----
# File Description:
# Configuration file for CLEO SDM kokkostools example with constant thermodynamics.
# Note: The initial superdroplets data read from file "initsupers_filename" can be made with
# CLEO's cleopy module (see Python script "create_initsuperdropsbinary_script.py" for example of usage).
# Likewise the "grid_filename" can be made using cleopy (see "create_gbxboundariesbinary_script.py"),
# and so can the thermodynamics files when using coupled thermodynamics "fromfile".
#

### SDM Runtime Parameters ###
domain:
  nspacedims : 3                                          # no. of spatial dimensions to model
  ngbxs : 1800                                            # total number of Gbxs
  maxnsupers: 7200                                        # maximum number of SDs

timesteps:
  CONDTSTEP : 1                                           # time between SD condensation [s]
  COLLTSTEP : 1                                           # time between SD collision [s]
  MOTIONTSTEP : 3                                         # time between SDM motion [s]
  COUPLTSTEP : 600                                        # time between dynamic couplings [s]
  OBSTSTEP : 10                                           # time between SDM observations [s]
  T_END : 1200                                            # time span of integration from 0s to T_END [s]

### Initialisation Parameters ###
inputfiles:
  constants_filename : ./libs/cleoconstants.hpp          # name of file for values of physical constants
  grid_filename : ./build/share/kokkostools_dimlessGBxboundaries.dat    # binary filename for initialisation of GBxs / GbxMaps

initsupers:
  type: frombinary                                        # type of initialisation of super-droplets
  initsupers_filename : ./build/share/kokkostools_dimlessSDsinit_run0.dat    # binary filename for initialisation of SDs

### Output Parameters ###
outputdata:
  setup_filename : ./build/share/kokkostools_setup_run0.txt  # .txt filename to copy configuration to
  zarrbasedir : ./build/share/kokkostools_sol_run0.zarr      # zarr store base directory
  maxchunk : 2500000                                         # maximum no. of elements in chunks of zarr store array

### Microphysics Parameters ###
microphysics:
  condensation:
    do_alter_thermo : false                               # true = cond/evap alters the thermodynamic state
    maxniters : 50                                        # maximum no. iterations of Newton Raphson Method
    MINSUBTSTEP : 0.1                                     # minimum subtimestep in cases of substepping [s]
    rtol : 0.0                                            # relative tolerance for implicit Euler integration
    atol : 0.01                                           # absolute tolerance for implicit Euler integration

### Coupled Dynamics Parameters ###
coupled_dynamics:
  type : fromfile                                         # type of coupled dynamics to configure
  press : ./build/share/kokkostools_dimlessthermo_press.dat             # binary filename for pressure
  temp : ./build/share/kokkostools_dimlessthermo_temp.dat               # binary filename for temperature
  qvap : ./build/share/kokkostools_dimlessthermo_qvap.dat               # binary filename for vapour mixing ratio
  qcond : ./build/share/kokkostools_dimlessthermo_qcond.dat             # binary filename for liquid mixing ratio
  wvel : ./build/share/kokkostools_dimlessthermo_wvel.dat               # binary filename for vertical (coord3) velocity
  uvel : ./build/share/kokkostools_dimlessthermo_uvel.dat               # binary filename for eastwards (coord1) velocity
  vvel : ./build/share/kokkostools_dimlessthermo_vvel.dat               # binary filename for northwards (coord2) velocity
