---
# ----- CLEO -----
# File: const2d_config.yaml
# Project: config
# Created Date: Wednesday 17th April 2024
# Author: Clara Bayley (CB)
# Additional Contributors:
# -----
# Last Modified: Wednesday 17th April 2024
# Modified By: CB
# -----
# License: BSD 3-Clause "New" or "Revised" License
# https://opensource.org/licenses/BSD-3-Clause
# -----
# Copyright (c) 2023 MPI-M, Clara Bayley
# -----
# File Description:
# Configuration file for CLEO 2-D example with constant thermodynamics read from a file.
# Note: The inital superdroplets data read from file "initsupers_filename" can be made with
# CLEO's pySD module (see Python script "create_initsuperdropsbinary_script.py" for usage).
# Likewise the "grid_filename" can be made using pySD (see "create_gbxboundariesbinary_script.py"),
# and so can the thermodynamics files when using coupled thermodynamics "fromfile".
#

### SDM Runtime Parameters ###
domain:
  nspacedims : 2                                              # no. of spatial dimensions to model
  ngbxs : 400                                                 # total number of Gbxs
  maxnsupers: 960                                             # maximum number of SDs

timesteps:
  CONDTSTEP : 1                                               # time between SD condensation [s]
  COLLTSTEP : 1                                               # time between SD collision [s]
  MOTIONTSTEP : 2                                             # time between SDM motion [s]
  COUPLTSTEP : 7200                                           # time between dynamic couplings [s]
  OBSTSTEP : 120                                              # time between SDM observations [s]
  T_END : 7200                                                # time span of integration from 0s to T_END [s]

### Initialisation Parameters ###
inputfiles:
  constants_filename : ../libs/cleoconstants.hpp              # name of file for values of physical constants
  grid_filename : ./share/const2d_dimlessGBxboundaries.dat    # binary filename for initialisation of GBxs / GbxMaps

initsupers:
  type: frombinary                                            # type of initialisation of super-droplets
  initsupers_filename : ./share/const2d_dimlessSDsinit.dat    # binary filename for initialisation of SDs

### Output Parameters ###
outputdata:
  setup_filename : ./bin/const2d_setup.txt                    # .txt filename to copy configuration to
  stats_filename : ./bin/const2d_stats.txt                    # .txt file to output runtime statistics to
  zarrbasedir : ./bin/const2d_sol.zarr                        # zarr store base directory
  maxchunk : 2500000                                          # maximum no. of elements in chunks of zarr store array

### Microphysics Parameters ###
microphysics:
  condensation:
    do_alter_thermo : false                                   # true = cond/evap alters the thermodynamic state
    niters : 2                                                # no. iterations of Newton Raphson Method before testing for convergence
    SUBTSTEP : 0.1                                            # smallest subtimestep in cases of substepping [s]
    rtol : 0.0                                                # relative tolerance for implicit Euler integration
    atol : 0.01                                               # abolute tolerance for implicit Euler integration

### Coupled Dynamics Parameters ###
coupled_dynamics:
  type : fromfile                                             # type of coupled dynamics to configure
  press : ./share/const2d_dimlessthermo_press.dat             # binary filename for pressure
  temp : ./share/const2d_dimlessthermo_temp.dat               # binary filename for temperature
  qvap : ./share/const2d_dimlessthermo_qvap.dat               # binary filename for vapour mixing ratio
  qcond : ./share/const2d_dimlessthermo_qcond.dat             # binary filename for liquid mixing ratio
  wvel : ./share/const2d_dimlessthermo_wvel.dat               # binary filename for vertical (coord3) velocity
  uvel : ./share/const2d_dimlessthermo_uvel.dat               # binary filename for eastwards (coord1) velocity
