# ----- CLEO -----
# File: boxmodel_condcoll_config.yaml
# Project: config
# Created Date: Wednesday 17th April 2024
# Author: Clara Bayley (CB)
# Additional Contributors:
# -----
# License: BSD 3-Clause "New" or "Revised" License
# https://opensource.org/licenses/BSD-3-Clause
# -----
# Copyright (c) 2023 MPI-M, Clara Bayley
# -----
# File Description:
# Configuration file for example of collisions and condensation in CLEO SDM 0-D box model.
# Note: The initial superdroplets data read from file "initsupers_filename" can be made with
# CLEO's cleopy module (see Python script "create_initsuperdropsbinary_script.py" for example of usage).
# Likewise the "grid_filename" can be made using cleopy (see "create_gbxboundariesbinary_script.py"),
# and so can the thermodynamics files when using coupled thermodynamics "fromfile".
#

### Initialization Parameters for constthermo2d_inputfiles.py ###
python_inputfiles:
  zgrid_max: 100                               # domain size in z [m]
  xgrid_max: 100                               # domain size in x [m]
  ygrid_max: 100                               # domain size in y [m]
  zgrid_ngbxs: 1                               # z direction ngbxs <- note(!) zgrid_ngbxs * xgrid_ngbxs == ngbxs (see below)
  xgrid_ngbxs: 1                               # x direction ngbxs <- note(!) zgrid_ngbxs * xgrid_ngbxs == ngbxs (see below)
  rspan:                                       # [min, max] range of radii to sample [m]
    - 3e-9
    - 3e-6
  geomeans:                                    # geometric means of bimodal Lognormal distribution
    - 0.02e-6
    - 0.15e-6
  geosigs:                                     # geometric stddevs of bimodal Lognormal distribution
    - 1.4
    - 1.6
  scalefacs:                                   # scale factors of peaks in bimodal Lognormal distribution
    - 0.6
    - 0.4
  numconc: 1e7                                 # total no. conc of real droplets [m^-3]
  thermo_PRESSz0: 101315                       # settings for thermodynamics profiles [Pa]
  thermo_THETA: 288.15                         # [K]
  thermo_WMAX: 0.0                             # [m/s]
  thermo_Zlength: 0                            # [m]
  thermo_Xlength: 0                            # [m]
  thermo_qvapmethod: "sratio"
  thermo_Zbase: 0                              # [m]
  thermo_sratios:                              # s_ratio [below, above] Zbase
    - 1.0025
    - 1.0025

### SDM Runtime Parameters ###
domain:
  nspacedims: 0                                                 # no. of spatial dimensions to model
  ngbxs: 1                                                      # total number of Gbxs
  maxnsupers: 1024                                              # maximum number of SDs

timesteps:
  CONDTSTEP: 1                                                  # time between SD condensation [s]
  COLLTSTEP: 1                                                  # time between SD collision [s]
  MOTIONTSTEP: 200                                              # time between SDM motion [s]
  COUPLTSTEP: 7200                                              # time between dynamic couplings [s]
  OBSTSTEP: 200                                                 # time between SDM observations [s]
  T_END: 7200                                                   # time span of integration from 0s to T_END [s]

### Initialisation Parameters ###
inputfiles:
  constants_filename: ./libs/cleoconstants.hpp                  # name of file for values of physical constants
  grid_filename: ./build/share/boxmodel_condcoll_dimlessGBxboundaries.dat   # binary filename for initialisation of GBxs / GbxMaps

initsupers:
  type: frombinary                                              # type of initialisation of super-droplets
  initsupers_filename: ./build/share/boxmodel_condcoll_dimlessSDsinit.dat   # binary filename for initialisation of SDs

### Output Parameters ###
outputdata:
  setup_filename: ./build/bin/boxmodel_condcoll_setup.txt               # .txt filename to copy configuration to
  zarrbasedir: ./build/bin/boxmodel_condcoll_sol.zarr                   # zarr store base directory
  maxchunk: 2500000                                             # maximum no. of elements in chunks of zarr store array

### Microphysics Parameters ###
microphysics:
  condensation:
    do_alter_thermo : false                                   # true = cond/evap alters the thermodynamic state
    maxniters : 50                                              # maximum no. iterations of Newton Raphson Method
    MINSUBTSTEP : 0.001                                         # minimum subtimestep in cases of substepping [s]
    rtol : 0.0                                                # relative tolerance for implicit Euler integration
    atol : 0.01                                               # absolute tolerance for implicit Euler integration

### Coupled Dynamics Parameters ###
coupled_dynamics:
  type : fromfile                                             # type of coupled dynamics to configure
  press : ./build/share/boxmodel_condcoll_dimlessthermo_press.dat             # binary filename for pressure
  temp : ./build/share/boxmodel_condcoll_dimlessthermo_temp.dat               # binary filename for temperature
  qvap : ./build/share/boxmodel_condcoll_dimlessthermo_qvap.dat               # binary filename for vapour mixing ratio
  qcond : ./build/share/boxmodel_condcoll_dimlessthermo_qcond.dat             # binary filename for liquid mixing ratio
  wvel : ./build/share/boxmodel_condcoll_dimlessthermo_wvel.dat               # binary filename for vertical (coord3) velocity
  uvel : ./build/share/boxmodel_condcoll_dimlessthermo_uvel.dat               # binary filename for eastwards (coord1) velocity
