---
# ----- CLEO -----
# File: config.yaml
# Project: config
# Created Date: Wednesday 17th April 2024
# Author: Clara Bayley (CB)
# Additional Contributors:
# -----
# Last Modified: Wednesday 17th April 2024
# Modified By: CB
# -----
# License: BSD 3-Clause "New" or "Revised" License
# https://opensource.org/licenses/BSD-3-Clause
# -----
# Copyright (c) 2023 MPI-M, Clara Bayley
# -----
# File Description:
# Configuration file for CLEO SDM coupled to a dynamics solver.
# Note: The inital superdroplets data read from file "initsupers_filename" can be made with
# CLEO's pySD module (see Python script "create_initsuperdropsbinary_script.py" for usage).
# Likewise the "grid_filename" can be made using pySD (see "create_gbxboundariesbinary_script.py"),
# and so can the thermodynamics files when using coupled thermodynamics "fromfile".
#

### SDM Runtime Parameters ###
domain:
  nspacedims : 1                                       # no. of spatial dimensions to model
  ngbxs : 41                                           # total number of Gbxs
  maxnsupers: 3048                                     # maximum number of SDs

timesteps:
  CONDTSTEP : 0.1                                      # time between SD condensation [s]
  COLLTSTEP : 1                                        # time between SD collision [s]
  MOTIONTSTEP : 2                                      # time between SDM motion [s]
  COUPLTSTEP : 8                                       # time between dynamic couplings [s]
  OBSTSTEP : 2                                         # time between SDM observations [s]
  T_END : 16                                           # time span of integration from 0s to T_END [s]

### Initialisation Parameters ###
inputfiles:
  constants_filename : ../libs/cleoconstants.hpp       # name of file for values of physical constants
  grid_filename : ./share/dimlessGBxboundaries.dat     # binary filename for initialisation of GBxs / GbxMaps

initsupers:
  type: frombinary                                     # type of initialisation of super-droplets
  initsupers_filename : ./share/dimlessSDsinit.dat     # binary filename for initialisation of SDs
  initnsupers: 1024                                    # initial no. of super-droplets to initialise

### Output Parameters ###
outputdata:
  setup_filename : ./bin/setup.txt                     # .txt filename to copy configuration to
  stats_filename : ./bin/stats.txt                     # .txt file to output runtime statistics to
  zarrbasedir : ./bin/SDMdata.zarr                     # zarr store base directory
  maxchunk : 2500000                                   # maximum no. of elements in chunks of zarr store array

### Microphysics Parameters ###
microphysics:
  condensation:
    do_alter_thermo : false                            # true = cond/evap alters the thermodynamic state
    niters : 2                                         # no. iterations of Newton Raphson Method before testing for convergence
    SUBTSTEP : 0.1                                     # smallest subtimestep in cases of substepping [s]
    rtol : 0.0                                         # relative tolerance for implicit Euler integration
    atol : 0.01                                        # abolute tolerance for implicit Euler integration

### Coupled Dynamics Parameters ###
coupled_dynamics:
  type : fromfile                                      # type of coupled dynamics to configure
  press : ./share/dimlessthermo_press.dat              # binary filename for pressure
  temp : ./share/dimlessthermo_temp.dat                # binary filename for temperature
  qvap : ./share/dimlessthermo_qvap.dat                # binary filename for vapour mixing ratio
  qcond : ./share/dimlessthermo_qcond.dat              # binary filename for liquid mixing ratio
  wvel : ./share/dimlessthermo_wvel.dat                # binary filename for vertical (coord3) velocity
  uvel : ./share/dimlessthermo_uvel.dat                # binary filename for eastwards (coord1) velocity
  vvel : ./share/dimlessthermo_vvel.dat                # binary filename for northwards (coord2) velocity

### Bounday Conditions Parameters ###
boundary_conditions:
  type: addsupersatdomaintop
  COORD3LIM: 800                                       # SDs added to domain with coord3 >= COORD3LIM [m]
  newnsupers: 1024                                     # number SDs to add to each gridbox above COORD3LIM
  DRYRADIUS: 1e-9                                      # dry radius of new super-droplets (for solute mass) [m]
  MINRADIUS: 1e-8                                      # minimum radius of new super-droplets [m]
  MAXRADIUS: 1e-4                                      # maximum radius of new super-droplets [m]
  NUMCONC_a: 2e8                                       # number conc. of 1st droplet lognormal dist [m^-3]
  GEOMEAN_a: 0.2e-6                                    # geometric mean radius of 1st lognormal dist [m]
  geosigma_a: 2.3                                      # geometric standard deviation of 1st lognormal dist
  NUMCONC_b: 4e8                                       # number conc. of 2nd droplet lognormal dist [m^-3]
  GEOMEAN_b: 3.5e-6                                    # geometric mean radius of 2nd lognormal dist [m]
  geosigma_b: 2.0                                      # geometric standard deviation of 2nd lognormal dist
