---
# ----- CLEO -----
# File: yac1_fromfile_config.txt
# Project: config
# Created Date: Thursday 18th April 2024
# Author: Clara Bayley (CB)
# Additional Contributors:
# -----
# Last Modified: Thursday 18th April 2024
# Modified By: CB
# -----
# License: BSD 3-Clause "New" or "Revised" License
# https://opensource.org/licenses/BSD-3-Clause
# -----
# Copyright (c) 2023 MPI-M, Clara Bayley
# -----
# File Description:
# Configuration file for contol example of 3D time varying thermodyanamics read from a file.
# Note: The inital superdroplets data read from file "initsupers_filename" can be made with
# CLEO's pySD module (see Python script "create_initsuperdropsbinary_script.py" for usage).
# Likewise the "grid_filename" can be made using pySD (see "create_gbxboundariesbinary_script.py"),
# and so can the thermodynamics files when using coupled thermodynamics "fromfile".
#

### SDM Runtime Parameters ###
domain:
  nspacedims : 3                                          # no. of spatial dimensions to model
  ngbxs : 2250                                            # total number of Gbxs
  maxnsupers: 2880                                        # maximum number of SDs

timesteps:
  CONDTSTEP : 2                                           # time between SD condensation [s]
  COLLTSTEP : 2                                           # time between SD collision [s]
  MOTIONTSTEP : 3                                         # time between SDM motion [s]
  COUPLTSTEP : 1800                                       # time between dynamic couplings [s]
  OBSTSTEP : 1800                                         # time between SDM observations [s]
  T_END : 7200                                            # time span of integration from 0s to T_END [s]

### Initialisation Parameters ###
inputfiles:
  constants_filename : ../libs/cleoconstants.hpp          # name of file for values of physical constants
  grid_filename : ./share/yac1_dimlessGBxboundaries.dat   # binary filename for initialisation of GBxs / GbxMaps

initsupers:
  type: frombinary                                        # type of initialisation of super-droplets
  initsupers_filename : ./share/yac1_dimlessSDsinit.dat   # binary filename for initialisation of SDs

### Output Parameters ###
outputdata:
  setup_filename : ./bin/yac1_setup.txt                   # .txt filename to copy configuration to
  stats_filename : ./bin/yac1_stats.txt                   # .txt file to output runtime statistics to
  zarrbasedir : ./bin/yac1_sol.zarr                       # zarr store base directory
  maxchunk : 2500000                                      # maximum no. of elements in chunks of zarr store array

### Coupled Dynamics Parameters ###
coupled_dynamics:
  type : fromfile                                         # type of coupled dynamics to configure
  press : ./share/yac1_dimlessthermo_press.dat            # binary filename for pressure
  temp : ./share/yac1_dimlessthermo_temp.dat              # binary filename for temperature
  qvap : ./share/yac1_dimlessthermo_qvap.dat              # binary filename for vapour mixing ratio
  qcond : ./share/yac1_dimlessthermo_qcond.dat            # binary filename for liquid mixing ratio
  wvel : ./share/yac1_dimlessthermo_wvel.dat              # binary filename for vertical (coord3) velocity
  uvel : ./share/yac1_dimlessthermo_uvel.dat              # binary filename for eastwards (coord1) velocity
  vvel : ./share/yac1_dimlessthermo_vvel.dat              # binary filename for eastwards (coord1) velocity
