name: pre-commit

on: pull_request

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Python setup
      uses: actions/setup-python@v5

    - name: Pre-commit run
      uses: pre-commit/action@v3.0.1
